spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:mysql://localhost:3306/springsecuritydb
    username: springsecurity
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 7000

jwt:
  secret:
    key: secrectkey123